builds:
  - binary: "kadiog"
    goos:
      - windows
      - darwin
      - linux
    goarch: 
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: kadiog
    homepage: https://github.com/akifkadioglu/kadiog-cli
    tap:
      owner: akifkadioglu
      name: kadiog-cli
    commit_author: 
      name: akifkadioglu
      email: akifkadioglu@yaani.com
  
checksum:
  name_template: 'checksums.txt'