# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kadiog < Formula
  desc ""
  homepage "https://github.com/akifkadioglu/kadiog-cli"
  version "0.0.6"

  on_macos do
    url "https://github.com/akifkadioglu/kadiog-cli/releases/download/v0.0.6/kadiog-cli_0.0.6_darwin_all.tar.gz"
    sha256 "31c54b855d8f11b84637dbe9f9fc138e9ce500ae73c3e8e563abcaf2128fb0e6"

    def install
      bin.install "kadiog-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akifkadioglu/kadiog-cli/releases/download/v0.0.6/kadiog-cli_0.0.6_linux_arm64.tar.gz"
      sha256 "764e32a4d434dffe2adca3d807e939689c9f182b7cfb32a28605166972f9353a"

      def install
        bin.install "kadiog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akifkadioglu/kadiog-cli/releases/download/v0.0.6/kadiog-cli_0.0.6_linux_amd64.tar.gz"
      sha256 "229606fd17995d6085984e33b9c81402f8087e0d85594d324c36585d45a08919"

      def install
        bin.install "kadiog"
      end
    end
  end
end
