# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kadiog < Formula
  desc ""
  homepage "https://github.com/akifkadioglu/kadiog-cli"
  version "0.0.4"

  on_macos do
    url "https://github.com/akifkadioglu/kadiog-cli/releases/download/v0.0.4/kadiog-cli_0.0.4_darwin_all.tar.gz"
    sha256 "c766ce11daa99a5c841c990931e933b0393ded43c4316cee61760a893f2fdfd0"

    def install
      bin.install "kadiog-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akifkadioglu/kadiog-cli/releases/download/v0.0.4/kadiog-cli_0.0.4_linux_arm64.tar.gz"
      sha256 "d294ae01c8e167322ec6368b52d1a4cd76c57b3944d7139d74651ee0d7a60645"

      def install
        bin.install "kadiog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akifkadioglu/kadiog-cli/releases/download/v0.0.4/kadiog-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "9e432893c48d4229e2855f1bf3cc1b6c09e1019cc7b412a058d229347875bbe8"

      def install
        bin.install "kadiog"
      end
    end
  end
end
