# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kadiog < Formula
  desc ""
  homepage "https://github.com/akifkadioglu/kadiog-cli"
  version "0.0.3"

  on_macos do
    url "https://github.com/akifkadioglu/kadiog-cli/releases/download/v0.0.3/kadiog-cli_0.0.3_darwin_all.tar.gz"
    sha256 "b6ad9df3247fe3973901259482adfc7f17c16b482f9d8238ea3dc45377f601f4"

    def install
      bin.install "kadiog-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/akifkadioglu/kadiog-cli/releases/download/v0.0.3/kadiog-cli_0.0.3_linux_amd64.tar.gz"
      sha256 "b9acd1bd2feec5dc8d27c3114793e6af9f96b932e856cc0cd32cfe3590ddd240"

      def install
        bin.install "kadiog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akifkadioglu/kadiog-cli/releases/download/v0.0.3/kadiog-cli_0.0.3_linux_arm64.tar.gz"
      sha256 "248210e40042d2340ed855378b6640350b771da9e15a6f2dd993305c49c48cf9"

      def install
        bin.install "kadiog"
      end
    end
  end
end
